AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 60

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
